### ISSUE TITLE
line 수

### ISSUE THREAD

**Issue by ellen24h** [NHNNEXT/2015-03-REAL-NPC#13]
```
  - 기간을 조절하는 기능
  - addition hover시 line수가 나오게
  - 팀별로 바꿔보기 
  - cf) 리커버별로 한다면 버블로 하면 어떨까?
  - hover시, 커밋당 평균 라인수를 보여주면 어떨까?
```

**Comment by jinus-laftel** [comment]
작업 예상 시간: 4~5시간
목요일 저녁, 금요일 저녁에 나눠서 작업 예정

**Comment by jinus-laftel** [comment]
64c8b74 range query on /commits
81b77b0 ppmmCommit: show lines (not commits), rewrite some codes
7d37611 Commit line: range option
3e420d7 Commit lines: mode added, code refactored
dfaeab8 Merge branch 'ppmmLines' into master
